### ISSUE TITLE
Breaks Administ

### ISSUE THREAD

**Issue by i2h3** [nextcloud/files_downloadlimit#421]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Use the `stable30` version of [juliusknorr/nextcloud-docker-dev](https://github.com/juliusknorr/nextcloud-docker-dev). I set up fresh containers so it is in clean state.
2. Install `files_downloadlimit` app.
3. Go to "Sharing" in "Administration settings".

### Expected behaviour
Successfully render the settings page as in Nextcloud AiO deployments.

### Actual behaviour

<details>
<summary>Internal Server Error</summary>

# Internal Server Error

The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

## Technical details

Remote Address: 192.168.21.5
Request ID: zmD2h0tCcpKplFyopa1l
Type: Exception
Code: 0
Message: template file not found: template:admin
File: /var/www/html/lib/private/Template/TemplateFileLocator.php
Line: 38

## Trace

#0 /var/www/html/lib/private/legacy/OC_Template.php(88): OC\Template\TemplateFileLocator->find('admin')
#1 /var/www/html/lib/private/legacy/OC_Template.php(53): OC_Template->findTemplate('', 'files_downloadl...', 'admin')
#2 /var/www/html/lib/public/AppFramework/Http/TemplateResponse.php(183): OC_Template->__construct('files_downloadl...', 'admin', '')
#3 /var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php(118): OCP\AppFramework\Http\TemplateResponse->render()
#4 /var/www/html/apps/settings/lib/Controller/AdminSettingsController.php(74): OCA\Settings\Controller\AdminSettingsController->formatSettings(Array)
#5 /var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php(142): OCA\Settings\Controller\AdminSettingsController->getSettings('sharing')
#6 /var/www/html/apps/settings/lib/Controller/AdminSettingsController.php(58): OCA\Settings\Controller\AdminSettingsController->getIndexResponse('admin', 'sharing')
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\Settings\Controller\AdminSettingsController->index('sharing')
#8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Settings\Controller\AdminSettingsController), 'index')
#9 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Settings\Controller\AdminSettingsController), 'index')
#10 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('OCA\\Settings\\Co...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/settings/admin...')
#12 /var/www/html/index.php(24): OC::handleRequest()
#13 {main}

</details>

### Server configuration

**Web server:** 🤷🏻‍♀️

**Database:** 🤷🏻‍♀️

**PHP version:** 🤷🏻‍♀️

**Nextcloud version:** Nextcloud Hub 9 (30.0.2 RC1)

<details>
<summary>List of activated apps</summary>

```
Enabled:
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 2.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - lookup_server_connector: 1.18.0
  - oauth2: 1.18.1
  - provisioning_api: 1.20.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - systemtags: 1.20.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_oidc: 6.1.2
  - user_status: 1.10.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - encryption: 2.18.0
  - files_external: 1.22.0
  - testing: 1.20.0
  - user_ldap: 1.21.0
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
{
    "system": {
        "debug": true,
        "profiler": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-extra",
                "url": "\/apps-extra",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-shared",
                "url": "\/apps-shared",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-writable",
                "url": "\/apps-writable",
                "writable": true
            }
        ],
        "allow_local_remote_servers": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "skeletondirectory": "\/skeleton",
        "setup_create_db_user": false,
        "loglevel": 2,
        "log_query": false,
        "query_log_file": "\/shared\/log\/querylog-stable30.log",
        "query_log_file_requestid": "yes",
        "diagnostics.logging": false,
        "diagnostics.logging.threshold": 0,
        "log.condition": {
            "apps": [
                "diagnostics",
                "admin_audit"
            ]
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud",
            "stable30.local",
            "192.168.21.6",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.2.0",
        "overwrite.cli.url": "http:\/\/stable30.local",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "git",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "lookup_server": "",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "files_downloadlimit"
        ]
    }
}
```
</details>

### Browser

**Browser name:** Safari

**Browser version:** 18.1 (20619.2.8.11.10)

**Operating system:** macOS

**Comment by susnux** [comment]
You must not install v2.0.0 (from the appstore).
The app is no longer shipped on the appstore but only as a shipped app, so for developer setup you need to clone the repo and mount it into the docker container

**Comment by i2h3** [comment]
Oh, this was an old one I completely forgot. I switched to relying on the community Docker image about two years ago. It is much more suitable for client development workflows. The developer setups are unnecessarily complicated and fragile for that and I am not involved in server development at all. So this was not an issue anymore.
